name: Create artifact from install cache

on:
  workflow_dispatch:
    inputs:
      runner_id_version:
        description: "Cache Runner ID Version"
        required: true
        default: "1"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: _install
          key: krita-Windows-install-${{ github.event.inputs.runner_id_version }}
          restore-keys: |
            krita-Windows-install-

      - name: Compress _install folder with 7-Zip
        shell: pwsh
        run: |
          & "C:\Program Files\7-Zip\7z.exe" a -mx=9 _install.7z _install\

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: krita-install-cache
          path: _install.7z
          retention-days: 1
